# Generated by Django 3.0.7 on 2020-06-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('is_accepted', models.BooleanField(null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_requests', to='administration.Website')),
            ],
        ),
    ]
